# Planner-side search/safety sweep grid for predictive planner campaigns.
# Keys are merged into the algorithm config passed to map_runner.
variants:
  - name: baseline_like
    params:
      predictive_goal_weight: 5.0
      predictive_collision_weight: 0.4
      predictive_near_miss_weight: 0.05
      predictive_ttc_weight: 0.15
      predictive_ttc_distance: 0.8
      occupancy_weight: 0.3
      predictive_candidate_speeds: [0.0, 0.4, 0.7, 1.0]
      predictive_candidate_heading_deltas: [-0.785398, -0.392699, 0.0, 0.392699, 0.785398]

  - name: safety_ttc_strong
    params:
      predictive_goal_weight: 4.5
      predictive_collision_weight: 0.7
      predictive_near_miss_weight: 0.10
      predictive_ttc_weight: 0.45
      predictive_ttc_distance: 1.0
      occupancy_weight: 0.4
      predictive_candidate_speeds: [0.0, 0.3, 0.6, 0.9, 1.0]
      predictive_candidate_heading_deltas: [-1.047198, -0.523599, -0.261799, 0.0, 0.261799, 0.523599, 1.047198]

  - name: progress_biased_dense_lattice
    params:
      predictive_goal_weight: 6.0
      predictive_collision_weight: 0.45
      predictive_near_miss_weight: 0.08
      predictive_ttc_weight: 0.25
      predictive_ttc_distance: 0.9
      occupancy_weight: 0.25
      predictive_candidate_speeds: [0.0, 0.25, 0.5, 0.75, 1.0]
      predictive_candidate_heading_deltas: [-0.785398, -0.523599, -0.261799, 0.0, 0.261799, 0.523599, 0.785398]

  - name: risk_aware_adaptive
    params:
      predictive_goal_weight: 6.0
      predictive_collision_weight: 0.5
      predictive_near_miss_weight: 0.10
      predictive_ttc_weight: 0.30
      predictive_ttc_distance: 0.9
      predictive_progress_risk_weight: 2.2
      predictive_progress_risk_distance: 1.3
      predictive_hard_clearance_distance: 0.8
      predictive_hard_clearance_weight: 3.0
      predictive_adaptive_horizon_enabled: true
      predictive_horizon_boost_steps: 6
      predictive_near_field_distance: 2.6
      predictive_near_field_speed_cap: 0.65
      predictive_near_field_speed_samples: [0.1, 0.2, 0.35, 0.5]
      predictive_near_field_heading_deltas: [-1.570796, -1.047198, -0.785398, -0.523599, 0.0, 0.523599, 0.785398, 1.047198, 1.570796]
      predictive_robot_radius: 0.25
      predictive_pedestrian_radius: 0.25
      predictive_speed_clearance_gain: 0.6
      occupancy_weight: 0.25
      predictive_candidate_speeds: [0.0, 0.25, 0.5, 0.75, 1.0]
      predictive_candidate_heading_deltas: [-0.785398, -0.523599, -0.261799, 0.0, 0.261799, 0.523599, 0.785398]
