classic_interactions:
  - 101
  - 102
  - 103
  - 111
  - 112
  - 113
  - 121
  - 122
  - 123
  - 131

francis2023:
  - 201
  - 202
  - 203
  - 204
  - 205
  - 206
  - 207
  - 208
  - 209
  - 210

default:
  - 0
