scenarios:
- name: classic_merging_low
  map_file: ../../../maps/svg_maps/classic_merging.svg
  simulation_config:
    max_episode_steps: 600
    ped_density: 0.02
  robot_config: {}
  metadata:
    archetype: merging
    density: low
    flow: converging
    groups: 0.0
    plausibility:
      status: unverified
      verified_on: null
      verified_by: null
      method: null
      notes: null
      metrics:
        min_distance: 11.684504594613694
        mean_distance: 15.03093438194068
        robot_ped_within_5m_frac: 0.0
        ped_force_mean: 0.10955040649701536
        force_q95: 0.3042751249156429
      metrics_updated_on: '2026-01-29T14:02:05.787139+01:00'
  seeds:
  - 151
  - 152
  - 153
- name: classic_merging_medium
  map_file: ../../../maps/svg_maps/classic_merging.svg
  simulation_config:
    max_episode_steps: 600
    ped_density: 0.05
  robot_config: {}
  metadata:
    archetype: merging
    density: medium
    flow: converging
    groups: 0.0
    plausibility:
      status: unverified
      verified_on: null
      verified_by: null
      method: null
      notes: null
      metrics:
        min_distance: 11.552651408272753
        mean_distance: 15.347102347198968
        robot_ped_within_5m_frac: 0.0
        ped_force_mean: 0.35186565033233397
        force_q95: 1.6337592150786728
      metrics_updated_on: '2026-01-29T14:02:05.787139+01:00'
  seeds:
  - 151
  - 152
  - 153
