scenarios:
- name: classic_crossing_low
  map_file: ../../../maps/svg_maps/classic_crossing.svg
  simulation_config:
    max_episode_steps: 600
    ped_density: 0.02
  robot_config: {}
  metadata:
    archetype: crossing
    density: low
    flow: bi
    groups: 0.0
    plausibility:
      status: unverified
      verified_on: null
      verified_by: null
      method: null
      notes: null
      metrics:
        min_distance: 4.365665890014939
        mean_distance: 8.047491178561614
        robot_ped_within_5m_frac: 0.25510204081632654
        ped_force_mean: 0.1292702987830097
        force_q95: 0.43954235832374555
      metrics_updated_on: '2026-01-29T14:02:05.787139+01:00'
  seeds:
  - 101
  - 102
  - 103
- name: classic_crossing_medium
  map_file: ../../../maps/svg_maps/classic_crossing.svg
  simulation_config:
    max_episode_steps: 600
    ped_density: 0.05
  robot_config: {}
  metadata:
    archetype: crossing
    density: medium
    flow: bi
    groups: 0.0
    plausibility:
      status: unverified
      verified_on: null
      verified_by: null
      method: null
      notes: null
      metrics:
        min_distance: 3.802777867006195
        mean_distance: 7.368776496951828
        robot_ped_within_5m_frac: 0.3565217391304348
        ped_force_mean: 0.08985354084658885
        force_q95: 0.25964348565495887
      metrics_updated_on: '2026-01-29T14:02:05.787139+01:00'
  seeds:
  - 101
  - 102
  - 103
- name: classic_crossing_high
  map_file: ../../../maps/svg_maps/classic_crossing.svg
  simulation_config:
    max_episode_steps: 600
    ped_density: 0.08
  robot_config: {}
  metadata:
    archetype: crossing
    density: high
    flow: bi
    groups: 0.0
    plausibility:
      status: unverified
      verified_on: null
      verified_by: null
      method: null
      notes: null
      metrics:
        min_distance: 4.641344481257215
        mean_distance: 8.466612390284483
        robot_ped_within_5m_frac: 0.19090909090909092
        ped_force_mean: 0.1475821043264511
        force_q95: 0.5812386467828754
      metrics_updated_on: '2026-01-29T14:02:05.787139+01:00'
  seeds:
  - 101
  - 102
  - 103
