scenarios:
- name: classic_overtaking_low
  map_file: ../../../maps/svg_maps/classic_overtaking.svg
  simulation_config:
    max_episode_steps: 600
    ped_density: 0.02
  robot_config: {}
  metadata:
    archetype: overtaking
    density: low
    flow: uni
    groups: 0.0
    plausibility:
      status: unverified
      verified_on: null
      verified_by: null
      method: null
      notes: null
      metrics:
        min_distance: 12.425307885671545
        mean_distance: 13.715366524915854
        robot_ped_within_5m_frac: 0.0
        ped_force_mean: 0.08569101091714941
        force_q95: 0.25655119899235573
      metrics_updated_on: '2026-01-29T14:02:05.787139+01:00'
  seeds:
  - 121
  - 122
  - 123
- name: classic_overtaking_medium
  map_file: ../../../maps/svg_maps/classic_overtaking.svg
  simulation_config:
    max_episode_steps: 600
    ped_density: 0.05
  robot_config: {}
  metadata:
    archetype: overtaking
    density: medium
    flow: uni
    groups: 0.0
    plausibility:
      status: unverified
      verified_on: null
      verified_by: null
      method: null
      notes: null
      metrics:
        min_distance: 11.840274186198965
        mean_distance: 13.296503402628687
        robot_ped_within_5m_frac: 0.0
        ped_force_mean: 0.07227631736829081
        force_q95: 0.28029133248010496
      metrics_updated_on: '2026-01-29T14:02:05.787139+01:00'
  seeds:
  - 121
  - 122
  - 123
