scenarios:
- name: classic_merging_low
  map_file: ../../../maps/svg_maps/classic_merging.svg
  simulation_config:
    max_episode_steps: 600
    ped_density: 0.02
  robot_config: {}
  metadata:
    archetype: merging
    density: low
    flow: converging
    groups: 0.0
  seeds:
  - 151
  - 152
  - 153
- name: classic_merging_medium
  map_file: ../../../maps/svg_maps/classic_merging.svg
  simulation_config:
    max_episode_steps: 600
    ped_density: 0.05
  robot_config: {}
  metadata:
    archetype: merging
    density: medium
    flow: converging
    groups: 0.0
  seeds:
  - 151
  - 152
  - 153
