scenarios:
- name: classic_crossing_low
  map_file: ../../../maps/svg_maps/classic_crossing.svg
  simulation_config:
    max_episode_steps: 600
    ped_density: 0.02
  robot_config: {}
  metadata:
    archetype: crossing
    label: cross plaza circulation
    density: low
    flow: bi
    groups: 0.0
    plausibility:
      status: verified
      verified_on: '2026-01-29'
      verified_by: ll7
      method: null
      notes: null
      metrics:
        min_distance: 1.5038082226149008
        mean_distance: 4.837551658389521
        robot_ped_within_5m_frac: 0.6143514468098895
        ped_force_mean: 0.19858230503498386
        force_q95: 0.7932805373669755
      metrics_updated_on: '2026-01-29T16:35:27.389871+01:00'
  seeds:
  - 101
  - 102
  - 103
- name: classic_crossing_medium
  map_file: ../../../maps/svg_maps/classic_crossing.svg
  simulation_config:
    max_episode_steps: 600
    ped_density: 0.05
  robot_config: {}
  metadata:
    archetype: crossing
    label: cross plaza circulation
    density: medium
    flow: bi
    groups: 0.0
    plausibility:
      status: verified
      verified_on: '2026-01-29'
      verified_by: ll7
      method: null
      notes: null
      metrics:
        min_distance: 1.8787397583134198
        mean_distance: 3.315186080462676
        robot_ped_within_5m_frac: 0.9045047993019196
        ped_force_mean: 0.233220156028614
        force_q95: 0.9530187782031074
      metrics_updated_on: '2026-01-29T16:35:27.389871+01:00'
  seeds:
  - 101
  - 102
  - 103
- name: classic_crossing_high
  map_file: ../../../maps/svg_maps/classic_crossing.svg
  simulation_config:
    max_episode_steps: 600
    ped_density: 0.08
  robot_config: {}
  metadata:
    archetype: crossing
    label: cross plaza circulation
    density: high
    flow: bi
    groups: 0.0
    plausibility:
      status: verified
      verified_on: '2026-01-29'
      verified_by: ll7
      method: null
      notes: null
      metrics:
        min_distance: 2.041250996832936
        mean_distance: 3.0957286401622004
        robot_ped_within_5m_frac: 1.0
        ped_force_mean: 0.26272504925094964
        force_q95: 1.0745741384120373
      metrics_updated_on: '2026-01-29T16:35:27.389871+01:00'
  seeds:
  - 101
  - 102
  - 103
