scenarios:
- name: classic_head_on_corridor_low
  map_file: ../../../maps/svg_maps/classic_head_on_corridor.svg
  simulation_config:
    max_episode_steps: 500
    ped_density: 0.02
  robot_config: {}
  metadata:
    archetype: head_on_corridor
    density: low
    flow: bi
    groups: 0.0
    plausibility:
      status: unverified
      verified_on: null
      verified_by: null
      method: null
      notes: null
      metrics:
        min_distance: 3.0967744282640193
        mean_distance: 5.8662763977389805
        robot_ped_within_5m_frac: 0.48704663212435234
        ped_force_mean: 0.11289599781419911
        force_q95: 0.5872665021233816
      metrics_updated_on: '2026-01-30T10:19:37.701701+01:00'
  seeds:
  - 111
  - 112
  - 113
- name: classic_head_on_corridor_medium
  map_file: ../../../maps/svg_maps/classic_head_on_corridor.svg
  simulation_config:
    max_episode_steps: 500
    ped_density: 0.05
  robot_config: {}
  metadata:
    archetype: head_on_corridor
    density: medium
    flow: bi
    groups: 0.0
    plausibility:
      status: unverified
      verified_on: null
      verified_by: null
      method: null
      notes: null
      metrics:
        min_distance: 2.995534203231526
        mean_distance: 5.147454316188918
        robot_ped_within_5m_frac: 0.58
        ped_force_mean: 0.10079726185076565
        force_q95: 0.5506129400923814
      metrics_updated_on: '2026-01-30T10:19:37.701701+01:00'
  seeds:
  - 111
  - 112
  - 113
