scenarios:
- name: classic_crossing_low
  map_file: ../../../maps/svg_maps/classic_crossing.svg
  simulation_config:
    max_episode_steps: 600
    ped_density: 0.02
  robot_config: {}
  metadata:
    archetype: crossing
    density: low
    flow: bi
    groups: 0.0
  seeds:
  - 101
  - 102
  - 103
- name: classic_crossing_medium
  map_file: ../../../maps/svg_maps/classic_crossing.svg
  simulation_config:
    max_episode_steps: 600
    ped_density: 0.05
  robot_config: {}
  metadata:
    archetype: crossing
    density: medium
    flow: bi
    groups: 0.0
  seeds:
  - 101
  - 102
  - 103
- name: classic_crossing_high
  map_file: ../../../maps/svg_maps/classic_crossing.svg
  simulation_config:
    max_episode_steps: 600
    ped_density: 0.08
  robot_config: {}
  metadata:
    archetype: crossing
    density: high
    flow: bi
    groups: 0.0
  seeds:
  - 101
  - 102
  - 103
