scenarios:
- name: classic_t_intersection_low
  map_file: ../../../maps/svg_maps/classic_t_intersection.svg
  simulation_config:
    max_episode_steps: 500
    ped_density: 0.02
  robot_config: {}
  metadata:
    archetype: t_intersection
    density: low
    flow: bi
    groups: 0.0
    plausibility:
      status: unverified
      verified_on: null
      verified_by: null
      method: null
      notes: null
      metrics:
        min_distance: 8.420087922065619
        mean_distance: 13.272042321456812
        robot_ped_within_5m_frac: 0.0
        ped_force_mean: 0.18387018318548726
        force_q95: 0.5227861895561289
      metrics_updated_on: '2026-01-30T10:19:37.701701+01:00'
  seeds:
  - 161
  - 162
  - 163
- name: classic_t_intersection_medium
  map_file: ../../../maps/svg_maps/classic_t_intersection.svg
  simulation_config:
    max_episode_steps: 500
    ped_density: 0.05
  robot_config: {}
  metadata:
    archetype: t_intersection
    density: medium
    flow: bi
    groups: 0.0
    plausibility:
      status: unverified
      verified_on: null
      verified_by: null
      method: null
      notes: null
      metrics:
        min_distance: 7.181055974470789
        mean_distance: 11.487834724814919
        robot_ped_within_5m_frac: 0.0
        ped_force_mean: 0.22735793405949617
        force_q95: 0.8424154514585526
      metrics_updated_on: '2026-01-30T10:19:37.701701+01:00'
  seeds:
  - 161
  - 162
  - 163
