scenarios:
- name: classic_realworld_bottleneck_medium
  map_file: ../../../maps/svg_maps/classic_realworld_bottleneck.svg
  simulation_config:
    max_episode_steps: 600
    ped_density: 0.05
  robot_config: {}
  metadata:
    archetype: bottleneck
    label: real-world narrow hallway bottleneck
    density: medium
    flow: bi
    groups: 0.0
  seeds:
  - 101
  - 102
  - 103
