scenarios:
- name: classic_doorway_low
  map_file: ../../../maps/svg_maps/classic_doorway.svg
  simulation_config:
    max_episode_steps: 500
    ped_density: 0.02
  robot_config: {}
  metadata:
    archetype: doorway
    density: low
    flow: bi
    groups: 0.0
    plausibility:
      status: unverified
      verified_on: null
      verified_by: null
      method: null
      notes: null
      metrics:
        min_distance: 4.8809022605295755
        mean_distance: 6.894347743498985
        robot_ped_within_5m_frac: 0.03773584905660377
        ped_force_mean: 0.04699638592286558
        force_q95: 0.1493465555897297
      metrics_updated_on: '2026-01-29T14:02:05.787139+01:00'
  seeds:
  - 141
  - 142
  - 143
- name: classic_doorway_medium
  map_file: ../../../maps/svg_maps/classic_doorway.svg
  simulation_config:
    max_episode_steps: 500
    ped_density: 0.05
  robot_config: {}
  metadata:
    archetype: doorway
    density: medium
    flow: bi
    groups: 0.0
    plausibility:
      status: unverified
      verified_on: null
      verified_by: null
      method: null
      notes: null
      metrics:
        min_distance: 5.50241113381485
        mean_distance: 6.633272956535718
        robot_ped_within_5m_frac: 0.0
        ped_force_mean: 0.24687886352322935
        force_q95: 1.5474817640953644
      metrics_updated_on: '2026-01-29T14:02:05.787139+01:00'
  seeds:
  - 141
  - 142
  - 143
