scenarios:
- name: classic_doorway_low
  map_file: ../../../maps/svg_maps/classic_doorway.svg
  simulation_config:
    max_episode_steps: 500
    ped_density: 0.02
    route_spawn_distribution: spread
    route_spawn_jitter_frac: 0.2
    max_peds_per_group: 1
  robot_config: {}
  metadata:
    archetype: doorway
    density: low
    flow: bi
    groups: 0.0
    plausibility:
      status: unverified
      verified_on: null
      verified_by: null
      method: null
      notes: null
      metrics:
        min_distance: 2.463720507545049
        mean_distance: 4.816876019796456
        robot_ped_within_5m_frac: 0.6435411099964484
        ped_force_mean: 0.3415082177106482
        force_q95: 1.2272777395106866
      metrics_updated_on: '2026-01-30T14:19:28.225110+01:00'
  seeds:
  - 141
  - 142
  - 143
- name: classic_doorway_medium
  map_file: ../../../maps/svg_maps/classic_doorway.svg
  simulation_config:
    max_episode_steps: 500
    ped_density: 0.05
    route_spawn_distribution: spread
    route_spawn_jitter_frac: 0.2
    max_peds_per_group: 1
  robot_config: {}
  metadata:
    archetype: doorway
    density: medium
    flow: bi
    groups: 0.0
    plausibility:
      status: unverified
      verified_on: null
      verified_by: null
      method: null
      notes: null
      metrics:
        min_distance: 2.0678184908531962
        mean_distance: 3.8315920323061348
        robot_ped_within_5m_frac: 0.7868823705030602
        ped_force_mean: 0.3252101197691243
        force_q95: 1.3760223536317078
      metrics_updated_on: '2026-01-30T14:19:28.225110+01:00'
  seeds:
  - 141
  - 142
  - 143
- name: classic_doorway_high
  map_file: ../../../maps/svg_maps/classic_doorway.svg
  simulation_config:
    max_episode_steps: 500
    ped_density: 0.08
    route_spawn_distribution: spread
    route_spawn_jitter_frac: 0.2
    max_peds_per_group: 1
  robot_config: {}
  metadata:
    archetype: doorway
    density: high
    flow: bi
    groups: 0.0
    plausibility:
      status: unverified
      verified_on: null
      verified_by: null
      method: null
      notes: null
      metrics:
        min_distance: 1.5266752306601346
        mean_distance: 3.6800348987218063
        robot_ped_within_5m_frac: 0.8078135977219347
        ped_force_mean: 0.2870675192361372
        force_q95: 1.1067593700206833
      metrics_updated_on: '2026-01-30T14:19:28.225110+01:00'
  seeds:
  - 141
  - 142
  - 143
