scenarios:
- name: classic_crossing_low
  map_file: ../../../maps/svg_maps/classic_crossing.svg
  simulation_config:
    max_episode_steps: 600
    ped_density: 0.02
  robot_config: {}
  metadata:
    archetype: crossing
    label: cross plaza circulation
    density: low
    flow: bi
    groups: 0.0
    plausibility:
      status: verified
      verified_on: '2026-01-29'
      verified_by: ll7
      method: null
      notes: null
      metrics:
        min_distance: 1.4799419279962416
        mean_distance: 2.6554891502926465
        robot_ped_within_5m_frac: 1.0
        ped_force_mean: 0.273002622248722
        force_q95: 0.9460728924645432
      metrics_updated_on: '2026-01-30T10:19:37.701701+01:00'
  seeds:
  - 101
  - 102
  - 103
- name: classic_crossing_medium
  map_file: ../../../maps/svg_maps/classic_crossing.svg
  simulation_config:
    max_episode_steps: 600
    ped_density: 0.05
  robot_config: {}
  metadata:
    archetype: crossing
    label: cross plaza circulation
    density: medium
    flow: bi
    groups: 0.0
    plausibility:
      status: verified
      verified_on: '2026-01-29'
      verified_by: ll7
      method: null
      notes: null
      metrics:
        min_distance: 0.058276832877591465
        mean_distance: 1.902916589466534
        robot_ped_within_5m_frac: 1.0
        ped_force_mean: 0.36967919494957535
        force_q95: 1.2832029731357877
      metrics_updated_on: '2026-01-30T10:19:37.701701+01:00'
  seeds:
  - 101
  - 102
  - 103
- name: classic_crossing_high
  map_file: ../../../maps/svg_maps/classic_crossing.svg
  simulation_config:
    max_episode_steps: 600
    ped_density: 0.08
  robot_config: {}
  metadata:
    archetype: crossing
    label: cross plaza circulation
    density: high
    flow: bi
    groups: 0.0
    plausibility:
      status: verified
      verified_on: '2026-01-29'
      verified_by: ll7
      method: null
      notes: null
      metrics:
        min_distance: 0.40730383038153933
        mean_distance: 1.6265772966244603
        robot_ped_within_5m_frac: 1.0
        ped_force_mean: 0.2962517846478671
        force_q95: 0.9589707383484916
      metrics_updated_on: '2026-01-30T10:19:37.701701+01:00'
  seeds:
  - 101
  - 102
  - 103
