scenarios:
- name: classic_head_on_corridor_low
  map_file: ../../../maps/svg_maps/classic_head_on_corridor.svg
  simulation_config:
    max_episode_steps: 500
    ped_density: 0.02
  robot_config: {}
  metadata:
    archetype: head_on_corridor
    density: low
    flow: bi
    groups: 0.0
    plausibility:
      status: unverified
      verified_on: null
      verified_by: null
      method: null
      notes: null
      metrics:
        min_distance: 4.6169752797191315
        mean_distance: 16.675511163869455
        robot_ped_within_5m_frac: 0.025906735751295335
        ped_force_mean: 0.13127799053566352
        force_q95: 0.438755735239528
      metrics_updated_on: '2026-01-29T14:02:05.787139+01:00'
  seeds:
  - 111
  - 112
  - 113
- name: classic_head_on_corridor_medium
  map_file: ../../../maps/svg_maps/classic_head_on_corridor.svg
  simulation_config:
    max_episode_steps: 500
    ped_density: 0.05
  robot_config: {}
  metadata:
    archetype: head_on_corridor
    density: medium
    flow: bi
    groups: 0.0
    plausibility:
      status: unverified
      verified_on: null
      verified_by: null
      method: null
      notes: null
      metrics:
        min_distance: 4.377081769762818
        mean_distance: 6.681716280454909
        robot_ped_within_5m_frac: 0.2613065326633166
        ped_force_mean: 0.13843676288415152
        force_q95: 0.4613055293692094
      metrics_updated_on: '2026-01-29T14:02:05.787139+01:00'
  seeds:
  - 111
  - 112
  - 113
