scenarios:
- name: classic_merging_low
  map_file: ../../../maps/svg_maps/classic_merging.svg
  simulation_config:
    max_episode_steps: 600
    ped_density: 0.02
  robot_config: {}
  metadata:
    archetype: merging
    density: low
    flow: converging
    groups: 0.0
    plausibility:
      status: unverified
      verified_on: null
      verified_by: null
      method: null
      notes: null
      metrics:
        min_distance: 12.00636995426902
        mean_distance: 15.375879946952068
        robot_ped_within_5m_frac: 0.0
        ped_force_mean: 0.14019089540575433
        force_q95: 0.49691467478753
      metrics_updated_on: '2026-01-30T10:19:37.701701+01:00'
  seeds:
  - 151
  - 152
  - 153
- name: classic_merging_medium
  map_file: ../../../maps/svg_maps/classic_merging.svg
  simulation_config:
    max_episode_steps: 600
    ped_density: 0.05
  robot_config: {}
  metadata:
    archetype: merging
    density: medium
    flow: converging
    groups: 0.0
    plausibility:
      status: unverified
      verified_on: null
      verified_by: null
      method: null
      notes: null
      metrics:
        min_distance: 12.367592566752736
        mean_distance: 16.17647678948835
        robot_ped_within_5m_frac: 0.0
        ped_force_mean: 0.19439736695134904
        force_q95: 0.6201993821708197
      metrics_updated_on: '2026-01-30T10:19:37.701701+01:00'
  seeds:
  - 151
  - 152
  - 153
