scenarios:
- name: classic_t_intersection_low
  map_file: ../../../maps/svg_maps/classic_t_intersection.svg
  simulation_config:
    max_episode_steps: 500
    ped_density: 0.02
  robot_config: {}
  metadata:
    archetype: t_intersection
    density: low
    flow: bi
    groups: 0.0
    plausibility:
      status: unverified
      verified_on: null
      verified_by: null
      method: null
      notes: null
      metrics:
        min_distance: 9.342135784790734
        mean_distance: 12.55526674055105
        robot_ped_within_5m_frac: 0.0
        ped_force_mean: 0.4989206329804127
        force_q95: 2.0299552746691645
      metrics_updated_on: '2026-01-29T14:02:05.787139+01:00'
  seeds:
  - 161
  - 162
  - 163
- name: classic_t_intersection_medium
  map_file: ../../../maps/svg_maps/classic_t_intersection.svg
  simulation_config:
    max_episode_steps: 500
    ped_density: 0.05
  robot_config: {}
  metadata:
    archetype: t_intersection
    density: medium
    flow: bi
    groups: 0.0
    plausibility:
      status: unverified
      verified_on: null
      verified_by: null
      method: null
      notes: null
      metrics:
        min_distance: 7.077286828260474
        mean_distance: 11.45740628594556
        robot_ped_within_5m_frac: 0.0
        ped_force_mean: 0.21060639512111437
        force_q95: 0.686255030574637
      metrics_updated_on: '2026-01-29T14:02:05.787139+01:00'
  seeds:
  - 161
  - 162
  - 163
