scenarios:
- name: classic_doorway_low
  map_file: ../../../maps/svg_maps/classic_doorway.svg
  simulation_config:
    max_episode_steps: 500
    ped_density: 0.02
    route_spawn_distribution: spread
    route_spawn_jitter_frac: 0.2
    max_peds_per_group: 1
  robot_config: {}
  metadata:
    archetype: doorway
    density: low
    flow: bi
    groups: 0.0
    plausibility:
      status: unverified
      verified_on: null
      verified_by: null
      method: null
      notes: null
      metrics:
        min_distance: 4.755770385520853
        mean_distance: 5.554907887449594
        robot_ped_within_5m_frac: 0.3283582089552239
        ped_force_mean: 0.38706965523701703
        force_q95: 2.156095635559882
      metrics_updated_on: '2026-01-30T10:19:37.701701+01:00'
  seeds:
  - 141
  - 142
  - 143
- name: classic_doorway_medium
  map_file: ../../../maps/svg_maps/classic_doorway.svg
  simulation_config:
    max_episode_steps: 500
    ped_density: 0.05
    route_spawn_distribution: spread
    route_spawn_jitter_frac: 0.2
    max_peds_per_group: 1
  robot_config: {}
  metadata:
    archetype: doorway
    density: medium
    flow: bi
    groups: 0.0
    plausibility:
      status: unverified
      verified_on: null
      verified_by: null
      method: null
      notes: null
      metrics:
        min_distance: 2.2752176250275595
        mean_distance: 5.315530140948203
        robot_ped_within_5m_frac: 0.3484848484848485
        ped_force_mean: 0.11240130598448837
        force_q95: 0.34472865483878185
      metrics_updated_on: '2026-01-30T10:19:37.701701+01:00'
  seeds:
  - 141
  - 142
  - 143
- name: classic_doorway_high
  map_file: ../../../maps/svg_maps/classic_doorway.svg
  simulation_config:
    max_episode_steps: 500
    ped_density: 0.08
    route_spawn_distribution: spread
    route_spawn_jitter_frac: 0.2
    max_peds_per_group: 1
  robot_config: {}
  metadata:
    archetype: doorway
    density: high
    flow: bi
    groups: 0.0
    plausibility:
      status: unverified
      verified_on: null
      verified_by: null
      method: null
      notes: null
      metrics:
        min_distance: 2.221994497380348
        mean_distance: 3.5144533569649155
        robot_ped_within_5m_frac: 0.8260869565217391
        ped_force_mean: 0.15766739777604932
        force_q95: 0.898601129192189
      metrics_updated_on: '2026-01-30T10:19:37.701701+01:00'
  seeds:
  - 141
  - 142
  - 143
