scenarios:
- name: classic_group_crossing_low
  map_file: ../../../maps/svg_maps/classic_group_crossing.svg
  simulation_config:
    max_episode_steps: 500
    ped_density: 0.02
    groups: 0.5
  robot_config: {}
  metadata:
    archetype: group_crossing
    density: low
    flow: bi
    groups: 0.5
    plausibility:
      status: unverified
      verified_on: null
      verified_by: null
      method: null
      notes: null
      metrics:
        min_distance: 7.720974649236953
        mean_distance: 8.968623335811508
        robot_ped_within_5m_frac: 0.0
        ped_force_mean: 0.07319254068220785
        force_q95: 0.2491729903403675
      metrics_updated_on: '2026-01-29T14:02:05.787139+01:00'
  seeds:
  - 171
  - 172
  - 173
- name: classic_group_crossing_medium
  map_file: ../../../maps/svg_maps/classic_group_crossing.svg
  simulation_config:
    max_episode_steps: 500
    ped_density: 0.05
    groups: 0.5
  robot_config: {}
  metadata:
    archetype: group_crossing
    density: medium
    flow: bi
    groups: 0.5
    plausibility:
      status: unverified
      verified_on: null
      verified_by: null
      method: null
      notes: null
      metrics:
        min_distance: 6.349739429273053
        mean_distance: 7.862708111443856
        robot_ped_within_5m_frac: 0.0
        ped_force_mean: 0.1476907011211691
        force_q95: 0.5293393454232289
      metrics_updated_on: '2026-01-29T14:02:05.787139+01:00'
  seeds:
  - 171
  - 172
  - 173
