scenarios:
- name: classic_overtaking_low
  map_file: ../../../maps/svg_maps/classic_overtaking.svg
  simulation_config:
    max_episode_steps: 600
    ped_density: 0.02
  robot_config: {}
  metadata:
    archetype: overtaking
    density: low
    flow: uni
    groups: 0.0
  seeds:
  - 121
  - 122
  - 123
- name: classic_overtaking_medium
  map_file: ../../../maps/svg_maps/classic_overtaking.svg
  simulation_config:
    max_episode_steps: 600
    ped_density: 0.05
  robot_config: {}
  metadata:
    archetype: overtaking
    density: medium
    flow: uni
    groups: 0.0
  seeds:
  - 121
  - 122
  - 123
