scenarios:
- name: classic_group_crossing_low
  map_file: ../../../maps/svg_maps/classic_group_crossing.svg
  simulation_config:
    max_episode_steps: 500
    ped_density: 0.02
    groups: 0.5
  robot_config: {}
  metadata:
    archetype: group_crossing
    density: low
    flow: bi
    groups: 0.5
    plausibility:
      status: unverified
      verified_on: null
      verified_by: null
      method: null
      notes: null
      metrics:
        min_distance: 0.18187999926581513
        mean_distance: 4.1209984784368086
        robot_ped_within_5m_frac: 0.6083333333333333
        ped_force_mean: 0.36972986575417627
        force_q95: 0.7218886404199658
      metrics_updated_on: '2026-01-30T10:19:37.701701+01:00'
  seeds:
  - 171
  - 172
  - 173
- name: classic_group_crossing_medium
  map_file: ../../../maps/svg_maps/classic_group_crossing.svg
  simulation_config:
    max_episode_steps: 500
    ped_density: 0.05
    groups: 0.5
  robot_config: {}
  metadata:
    archetype: group_crossing
    density: medium
    flow: bi
    groups: 0.5
    plausibility:
      status: unverified
      verified_on: null
      verified_by: null
      method: null
      notes: null
      metrics:
        min_distance: 0.037358269597714516
        mean_distance: 4.0707874055761835
        robot_ped_within_5m_frac: 0.6120689655172413
        ped_force_mean: 0.27021555788497204
        force_q95: 0.8073974207622258
      metrics_updated_on: '2026-01-30T10:19:37.701701+01:00'
  seeds:
  - 171
  - 172
  - 173
- name: classic_group_crossing_high
  map_file: ../../../maps/svg_maps/classic_group_crossing.svg
  simulation_config:
    max_episode_steps: 500
    ped_density: 0.08
    groups: 0.5
  robot_config: {}
  metadata:
    archetype: group_crossing
    density: high
    flow: bi
    groups: 0.5
    plausibility:
      status: unverified
      verified_on: null
      verified_by: null
      method: null
      notes: null
      metrics:
        min_distance: 0.037358269597714516
        mean_distance: 4.0707874055761835
        robot_ped_within_5m_frac: 0.6120689655172413
        ped_force_mean: 0.27021555788497204
        force_q95: 0.8073974207622258
      metrics_updated_on: '2026-01-30T10:19:37.701701+01:00'
  seeds:
  - 171
  - 172
  - 173