scenarios:
- name: classic_group_crossing_low
  map_file: ../../../maps/svg_maps/classic_group_crossing.svg
  simulation_config:
    max_episode_steps: 500
    ped_density: 0.04
    groups: 0.5
  robot_config: {}
  metadata:
    archetype: group_crossing
    density: low
    flow: bi
    groups: 0.5
    plausibility:
      status: verified
      verified_on: '2026-01-30'
      verified_by: ll7
      method: null
      notes: null
      metrics:
        min_distance: 2.786827502246117
        mean_distance: 7.229886758663069
        robot_ped_within_5m_frac: 0.27854876797388683
        ped_force_mean: 0.20199272314365463
        force_q95: 0.64291099435539
      metrics_updated_on: '2026-01-30T14:19:28.225110+01:00'
  seeds:
  - 171
  - 172
  - 173
- name: classic_group_crossing_medium
  map_file: ../../../maps/svg_maps/classic_group_crossing.svg
  simulation_config:
    max_episode_steps: 500
    ped_density: 0.08
    groups: 0.5
  robot_config: {}
  metadata:
    archetype: group_crossing
    density: medium
    flow: bi
    groups: 0.5
    plausibility:
      status: verified
      verified_on: '2026-01-30'
      verified_by: ll7
      method: null
      notes: null
      metrics:
        min_distance: 2.6337745513868533
        mean_distance: 5.827523727663918
        robot_ped_within_5m_frac: 0.3938562438705459
        ped_force_mean: 0.3374180570126427
        force_q95: 1.150662182566604
      metrics_updated_on: '2026-01-30T14:19:28.225110+01:00'
  seeds:
  - 171
  - 172
  - 173
- name: classic_group_crossing_high
  map_file: ../../../maps/svg_maps/classic_group_crossing.svg
  simulation_config:
    max_episode_steps: 500
    ped_density: 0.12
    groups: 0.5
  robot_config: {}
  metadata:
    archetype: group_crossing
    density: high
    flow: bi
    groups: 0.5
    plausibility:
      status: verified
      verified_on: '2026-01-30'
      verified_by: ll7
      method: null
      notes: null
      metrics:
        min_distance: 1.2462613789534065
        mean_distance: 4.577864020111103
        robot_ped_within_5m_frac: 0.5766262998921123
        ped_force_mean: 0.35675981000425605
        force_q95: 1.287504328477061
      metrics_updated_on: '2026-01-30T14:19:28.225110+01:00'
  seeds:
  - 171
  - 172
  - 173
