scenarios:
- name: classic_urban_crossing_medium
  map_file: ../../../maps/svg_maps/classic_urban_crossing.svg
  simulation_config:
    max_episode_steps: 600
    ped_density: 0.05
  robot_config: {}
  metadata:
    archetype: crossing
    label: urban crosswalk intersection
    density: medium
    flow: bi
    groups: 0.0
  seeds:
  - 101
  - 102
  - 103
