scenarios:
- name: classic_overtaking_low
  map_file: ../../../maps/svg_maps/classic_overtaking.svg
  simulation_config:
    max_episode_steps: 600
    ped_density: 0.02
  robot_config: {}
  metadata:
    archetype: overtaking
    density: low
    flow: uni
    groups: 0.0
    plausibility:
      status: unverified
      verified_on: null
      verified_by: null
      method: null
      notes: null
      metrics:
        min_distance: 10.270118207983272
        mean_distance: 11.622435969627
        robot_ped_within_5m_frac: 0.0
        ped_force_mean: 0.22336359147694868
        force_q95: 0.5328313060358923
      metrics_updated_on: '2026-01-30T10:19:37.701701+01:00'
  seeds:
  - 121
  - 122
  - 123
- name: classic_overtaking_medium
  map_file: ../../../maps/svg_maps/classic_overtaking.svg
  simulation_config:
    max_episode_steps: 600
    ped_density: 0.05
  robot_config: {}
  metadata:
    archetype: overtaking
    density: medium
    flow: uni
    groups: 0.0
    plausibility:
      status: unverified
      verified_on: null
      verified_by: null
      method: null
      notes: null
      metrics:
        min_distance: 9.648281444340713
        mean_distance: 11.179332845496239
        robot_ped_within_5m_frac: 0.0
        ped_force_mean: 0.17469417542623888
        force_q95: 0.45367729717835537
      metrics_updated_on: '2026-01-30T10:19:37.701701+01:00'
  seeds:
  - 121
  - 122
  - 123
