scenarios:
- name: classic_group_crossing_low
  map_file: ../../../maps/svg_maps/classic_group_crossing.svg
  simulation_config:
    max_episode_steps: 500
    ped_density: 0.02
    groups: 0.5
  robot_config: {}
  metadata:
    archetype: group_crossing
    density: low
    flow: bi
    groups: 0.5
  seeds:
  - 171
  - 172
  - 173
