scenarios:
- name: francis2023_exiting_elevator
  map_file: ../../../maps/svg_maps/francis2023/francis2023_exiting_elevator.svg
  simulation_config:
    max_episode_steps: 400
    ped_density: 0.0
  single_pedestrians:
  - id: h1
    goal_poi: poi_h1_goal
  robot_config: {}
  metadata:
    figure: 7o
    archetype: exiting_elevator
    flow: exit
    behavior: none
    plausibility:
      status: unverified
      verified_on: null
      verified_by: null
      method: null
      notes: null
      metrics:
        min_distance: 2.0155808933351076
        mean_distance: 4.0238370246585955
        robot_ped_within_5m_frac: 0.6794871794871795
        ped_force_mean: 0.2740323242633463
        force_q95: 0.5878322689899054
      metrics_updated_on: '2026-01-29T14:02:05.787139+01:00'
  seeds:
  - 237
  - 238
  - 239
