scenarios:
- name: francis2023_pedestrian_overtaking
  map_file: ../../../maps/svg_maps/francis2023/francis2023_ped_overtaking.svg
  simulation_config:
    max_episode_steps: 400
    ped_density: 0.0
  single_pedestrians:
  - id: h1
    goal_poi: poi_h1_goal
    speed_m_s: 0.8
    note: fast walker (tuning pending)
  robot_config: {}
  metadata:
    figure: 7c
    archetype: pedestrian_overtaking
    flow: uni
    behavior: fast_ped
    plausibility:
      status: unverified
      verified_on: null
      verified_by: null
      method: null
      notes: null
      metrics:
        min_distance: 0.2930505887352627
        mean_distance: 8.038215922481768
        robot_ped_within_5m_frac: 0.32367149758454106
        ped_force_mean: 0.259730501037114
        force_q95: 1.4043869337336736
      metrics_updated_on: '2026-01-29T14:02:05.787139+01:00'
  seeds:
  - 207
  - 208
  - 209
