scenarios:
- name: francis2023_leave_group
  map_file: ../../../maps/svg_maps/francis2023/francis2023_leave_group.svg
  simulation_config:
    max_episode_steps: 400
    ped_density: 0.0
  single_pedestrians:
  - id: h1
    role: leave
    goal_poi: poi_h1_goal
    note: leave group toward exit
  - id: h2
    goal: null
    role: wait
    note: group anchor (static)
  - id: h3
    goal: null
    role: wait
    note: group anchor (static)
  robot_config: {}
  metadata:
    figure: 7q
    archetype: leave_group
    flow: n/a
    behavior: leave
    plausibility:
      status: unverified
      verified_on: null
      verified_by: null
      method: null
      notes: null
      metrics:
        min_distance: 0.686514351852891
        mean_distance: 1.9617562333026033
        robot_ped_within_5m_frac: 1.0
        ped_force_mean: 0.7036381926794569
        force_q95: 2.8095291224768943
      metrics_updated_on: '2026-01-29T14:02:05.787139+01:00'
  seeds:
  - 258
  - 259
  - 260
