scenarios:
- name: francis2023_robot_crowding
  map_file: ../../../maps/svg_maps/francis2023/francis2023_robot_crowding.svg
  simulation_config:
    max_episode_steps: 400
    ped_density: 0.12
  robot_config: {}
  metadata:
    figure: 7y
    archetype: robot_crowding
    flow: crowd
    behavior: crowding
    plausibility:
      status: unverified
      verified_on: null
      verified_by: null
      method: null
      notes: null
      metrics:
        min_distance: 3.045685547216631
        mean_distance: 4.573849656079643
        robot_ped_within_5m_frac: 0.6715
        ped_force_mean: 0.5457873106030219
        force_q95: 1.6530126353850463
      metrics_updated_on: '2026-01-30T14:19:28.225110+01:00'
  seeds:
  - 273
  - 274
  - 275
