scenarios:
- name: francis2023_perpendicular_traffic
  map_file: ../../../maps/svg_maps/francis2023/francis2023_perpendicular_traffic.svg
  simulation_config:
    max_episode_steps: 400
    ped_density: 0.1
  robot_config: {}
  metadata:
    figure: 7w
    archetype: perpendicular_traffic
    flow: perpendicular
    behavior: traffic
    plausibility:
      status: unverified
      verified_on: null
      verified_by: null
      method: null
      notes: null
      metrics:
        min_distance: 5.882090702576283
        mean_distance: 8.068767231979212
        robot_ped_within_5m_frac: 0.0
        ped_force_mean: 0.34889783658665074
        force_q95: 1.360584539539841
      metrics_updated_on: '2026-01-29T14:02:05.787139+01:00'
  seeds:
  - 267
  - 268
  - 269
