scenarios:
- name: francis2023_narrow_doorway
  map_file: ../../../maps/svg_maps/francis2023/francis2023_narrow_doorway.svg
  simulation_config:
    max_episode_steps: 400
    ped_density: 0.0
  single_pedestrians:
  - id: h1
    goal_poi: poi_h1_goal
  robot_config: {}
  metadata:
    figure: 7k
    archetype: narrow_doorway
    flow: bi
    behavior: none
    plausibility:
      status: unverified
      verified_on: null
      verified_by: null
      method: null
      notes: null
      metrics:
        min_distance: 8.075823545897144
        mean_distance: 13.009187007220126
        robot_ped_within_5m_frac: 0.0
        ped_force_mean: 0.2539185042875203
        force_q95: 0.729154953602099
      metrics_updated_on: '2026-01-29T14:02:05.787139+01:00'
  seeds:
  - 225
  - 226
  - 227
