scenarios:
- name: francis2023_parallel_traffic
  map_file: ../../../maps/svg_maps/francis2023/francis2023_parallel_traffic.svg
  simulation_config:
    max_episode_steps: 400
    ped_density: 0.04
  robot_config: {}
  metadata:
    figure: 7v
    archetype: parallel_traffic
    flow: parallel
    behavior: traffic
    plausibility:
      status: unverified
      verified_on: null
      verified_by: null
      method: null
      notes: null
      metrics:
        min_distance: 1.8838989696842277
        mean_distance: 11.271154598399779
        robot_ped_within_5m_frac: 0.24731182795698925
        ped_force_mean: 0.2706974332667629
        force_q95: 0.8747119029834098
      metrics_updated_on: '2026-01-29T14:02:05.787139+01:00'
  seeds:
  - 264
  - 265
  - 266
