scenarios:
- name: francis2023_leading_human
  map_file: ../../../maps/svg_maps/francis2023/francis2023_down_path.svg
  simulation_config:
    max_episode_steps: 400
    ped_density: 0.0
  single_pedestrians:
  - id: h1
    goal: null
    role: follow
    role_target_id: robot:0
    role_offset:
    - -1.5
    - 0.0
    note: human follows robot (role follow)
  robot_config: {}
  metadata:
    figure: 7s
    archetype: leading_human
    flow: uni
    behavior: follow
    plausibility:
      status: unverified
      verified_on: null
      verified_by: null
      method: null
      notes: null
      metrics:
        min_distance: 0.9505961814969174
        mean_distance: 7.866358648808193
        robot_ped_within_5m_frac: 0.32338308457711445
        ped_force_mean: 0.1254311868215958
        force_q95: 0.4611098462815739
      metrics_updated_on: '2026-01-29T14:02:05.787139+01:00'
  seeds:
  - 249
  - 250
  - 251
