scenarios:
- name: francis2023_robot_crowding
  map_file: ../../../maps/svg_maps/francis2023/francis2023_robot_crowding.svg
  simulation_config:
    max_episode_steps: 400
    ped_density: 0.12
  robot_config: {}
  metadata:
    figure: 7y
    archetype: robot_crowding
    flow: crowd
    behavior: crowding
    plausibility:
      status: unverified
      verified_on: null
      verified_by: null
      method: null
      notes: null
      metrics:
        min_distance: 1.0604677903123112
        mean_distance: 3.003490934152792
        robot_ped_within_5m_frac: 0.8985507246376812
        ped_force_mean: 0.49017178614340706
        force_q95: 1.4755636714772555
      metrics_updated_on: '2026-01-29T14:02:05.787139+01:00'
  seeds:
  - 273
  - 274
  - 275
