scenarios:
- name: francis2023_parallel_traffic
  map_file: ../../../maps/svg_maps/francis2023/francis2023_parallel_traffic.svg
  simulation_config:
    max_episode_steps: 400
    ped_density: 0.04
  robot_config: {}
  metadata:
    figure: 7v
    archetype: parallel_traffic
    flow: parallel
    behavior: traffic
    plausibility:
      status: unverified
      verified_on: null
      verified_by: null
      method: null
      notes: null
      metrics:
        min_distance: 0.2154839791414925
        mean_distance: 3.0975129952197324
        robot_ped_within_5m_frac: 0.7946768060836502
        ped_force_mean: 0.2670086862400031
        force_q95: 0.916442501193047
      metrics_updated_on: '2026-01-30T10:19:37.701701+01:00'
  seeds:
  - 264
  - 265
  - 266
