scenarios:
- name: francis2023_entering_elevator
  map_file: ../../../maps/svg_maps/francis2023/francis2023_entering_elevator.svg
  simulation_config:
    max_episode_steps: 400
    ped_density: 0.0
  single_pedestrians:
  - id: h1
    goal_poi: poi_h1_goal
  robot_config: {}
  metadata:
    figure: 7n
    archetype: entering_elevator
    flow: enter
    behavior: none
    plausibility:
      status: unverified
      verified_on: null
      verified_by: null
      method: null
      notes: null
      metrics:
        min_distance: 2.6329627492537844
        mean_distance: 7.018890149273052
        robot_ped_within_5m_frac: 0.27527255921880417
        ped_force_mean: 0.1626901414381952
        force_q95: 0.42404303193127524
      metrics_updated_on: '2026-01-30T14:19:28.225110+01:00'
  seeds:
  - 234
  - 235
  - 236
