scenarios:
- name: francis2023_intersection_proceed
  map_file: ../../../maps/svg_maps/francis2023/francis2023_intersection_no_gesture.svg
  simulation_config:
    max_episode_steps: 400
    ped_density: 0.0
  single_pedestrians:
  - id: h1
    goal: null
    trajectory:
    - - 14.0
      - 17.5
    - - 14.0
      - 15.0
    - - 14.0
      - 4.0
    note: intersection proceed
  robot_config: {}
  metadata:
    figure: 7h
    archetype: intersection_proceed
    flow: cross
    behavior: proceed
    plausibility:
      status: unverified
      verified_on: null
      verified_by: null
      method: null
      notes: null
      metrics:
        min_distance: 3.498365984803269
        mean_distance: 6.628920827314485
        robot_ped_within_5m_frac: 0.34285714285714286
        ped_force_mean: 0.09369421668343393
        force_q95: 0.3419953727571229
      metrics_updated_on: '2026-01-30T10:19:37.701701+01:00'
  seeds:
  - 243
  - 244
  - 245
