scenarios:
- name: francis2023_circular_crossing
  map_file: ../../../maps/svg_maps/francis2023/francis2023_circular_crossing.svg
  simulation_config:
    max_episode_steps: 400
    ped_density: 0.06
  robot_config: {}
  metadata:
    figure: 7x
    archetype: circular_crossing
    flow: circular
    behavior: traffic
    plausibility:
      status: unverified
      verified_on: null
      verified_by: null
      method: null
      notes: null
      metrics:
        min_distance: 2.3052513595659803
        mean_distance: 4.982859775833658
        robot_ped_within_5m_frac: 0.45121951219512196
        ped_force_mean: 0.24492653342564616
        force_q95: 0.8603574186928482
      metrics_updated_on: '2026-01-30T10:19:37.701701+01:00'
  seeds:
  - 270
  - 271
  - 272
