scenarios:
- name: francis2023_entering_elevator
  map_file: ../../../maps/svg_maps/francis2023/francis2023_entering_elevator.svg
  simulation_config:
    max_episode_steps: 400
    ped_density: 0.0
  single_pedestrians:
  - id: h1
    goal_poi: poi_h1_goal
  robot_config: {}
  metadata:
    figure: 7n
    archetype: entering_elevator
    flow: enter
    behavior: none
    plausibility:
      status: unverified
      verified_on: null
      verified_by: null
      method: null
      notes: null
      metrics:
        min_distance: 2.2809629196912806
        mean_distance: 6.496598272701955
        robot_ped_within_5m_frac: 0.3492063492063492
        ped_force_mean: 0.17124649314558657
        force_q95: 0.4238179063711362
      metrics_updated_on: '2026-01-30T10:19:37.701701+01:00'
  seeds:
  - 234
  - 235
  - 236
