scenarios:
- name: francis2023_following_human
  map_file: ../../../maps/svg_maps/francis2023/francis2023_down_path.svg
  simulation_config:
    max_episode_steps: 400
    ped_density: 0.0
  single_pedestrians:
  - id: h1
    goal: null
    role: lead
    role_target_id: robot:0
    role_offset:
    - 2.0
    - 0.0
    note: human leads robot (role lead)
  robot_config: {}
  metadata:
    figure: 7r
    archetype: following_human
    flow: uni
    behavior: lead
    plausibility:
      status: unverified
      verified_on: null
      verified_by: null
      method: null
      notes: null
      metrics:
        min_distance: 1.483457370738618
        mean_distance: 7.826086665342063
        robot_ped_within_5m_frac: 0.3160296101329766
        ped_force_mean: 0.11548719787819786
        force_q95: 0.393256336079603
      metrics_updated_on: '2026-01-30T14:19:28.225110+01:00'
  seeds:
  - 246
  - 247
  - 248
