scenarios:
- name: francis2023_frontal_approach
  map_file: ../../../maps/svg_maps/francis2023/francis2023_frontal_approach.svg
  simulation_config:
    max_episode_steps: 400
    ped_density: 0.0
  single_pedestrians:
  - id: h1
    goal_poi: poi_h1_goal
  robot_config: {}
  metadata:
    figure: 7a
    archetype: frontal_approach
    flow: bi
    behavior: none
    plausibility:
      status: unverified
      verified_on: null
      verified_by: null
      method: null
      notes: null
      metrics:
        min_distance: 0.888590106819758
        mean_distance: 7.970047172180216
        robot_ped_within_5m_frac: 0.319047619047619
        ped_force_mean: 0.17783746501078582
        force_q95: 0.8825507003383919
      metrics_updated_on: '2026-01-30T10:19:37.701701+01:00'
  seeds:
  - 201
  - 202
  - 203
