scenarios:
- name: francis2023_accompanying_peer
  map_file: ../../../maps/svg_maps/francis2023/francis2023_down_path.svg
  simulation_config:
    max_episode_steps: 400
    ped_density: 0.0
  single_pedestrians:
  - id: h1
    goal: null
    role: accompany
    role_target_id: robot:0
    role_offset:
    - 0.0
    - 1.0
    note: side-by-side with robot
  robot_config: {}
  metadata:
    figure: 7t
    archetype: accompanying_peer
    flow: uni
    behavior: accompany
    plausibility:
      status: unverified
      verified_on: null
      verified_by: null
      method: null
      notes: null
      metrics:
        min_distance: 1.3178905131941312
        mean_distance: 7.831297162858541
        robot_ped_within_5m_frac: 0.31840796019900497
        ped_force_mean: 0.11345565579689039
        force_q95: 0.42343125240795
      metrics_updated_on: '2026-01-30T10:19:37.701701+01:00'
  seeds:
  - 252
  - 253
  - 254
