scenarios:
- name: francis2023_blind_corner
  map_file: ../../../maps/svg_maps/francis2023/francis2023_blind_corner.svg
  simulation_config:
    max_episode_steps: 400
    ped_density: 0.0
  single_pedestrians:
  - id: h1
    goal_poi: poi_h1_goal
  robot_config: {}
  metadata:
    figure: 7i
    archetype: blind_corner
    flow: bi
    behavior: none
    plausibility:
      status: unverified
      verified_on: null
      verified_by: null
      method: null
      notes: null
      metrics:
        min_distance: 0.39313912751896823
        mean_distance: 9.484048414106008
        robot_ped_within_5m_frac: 0.2536231884057971
        ped_force_mean: 0.16927294833809328
        force_q95: 0.8100995561585765
      metrics_updated_on: '2026-01-29T14:02:05.787139+01:00'
  seeds:
  - 219
  - 220
  - 221
