scenarios:
- name: francis2023_leading_human
  map_file: ../../../maps/svg_maps/francis2023/francis2023_down_path.svg
  simulation_config:
    max_episode_steps: 400
    ped_density: 0.0
  single_pedestrians:
  - id: h1
    goal: null
    role: follow
    role_target_id: robot:0
    role_offset:
    - -1.5
    - 0.0
    note: human follows robot (role follow)
  robot_config: {}
  metadata:
    figure: 7s
    archetype: leading_human
    flow: uni
    behavior: follow
    plausibility:
      status: unverified
      verified_on: null
      verified_by: null
      method: null
      notes: null
      metrics:
        min_distance: 1.3870452472855677
        mean_distance: 7.948761036366759
        robot_ped_within_5m_frac: 0.3180338840646543
        ped_force_mean: 0.13604703590208986
        force_q95: 0.46106699678358576
      metrics_updated_on: '2026-01-30T14:19:28.225110+01:00'
  seeds:
  - 249
  - 250
  - 251
