scenarios:
- name: francis2023_narrow_doorway
  map_file: ../../../maps/svg_maps/francis2023/francis2023_narrow_doorway.svg
  simulation_config:
    max_episode_steps: 400
    ped_density: 0.0
  single_pedestrians:
  - id: h1
    goal_poi: poi_h1_goal
  robot_config: {}
  metadata:
    figure: 7k
    archetype: narrow_doorway
    flow: bi
    behavior: none
    plausibility:
      status: unverified
      verified_on: null
      verified_by: null
      method: null
      notes: null
      metrics:
        min_distance: 5.719522860489053
        mean_distance: 8.143361921262386
        robot_ped_within_5m_frac: 0.0
        ped_force_mean: 0.05848146975193476
        force_q95: 0.32300781273340784
      metrics_updated_on: '2026-01-30T14:19:28.225110+01:00'
  seeds:
  - 225
  - 226
  - 227
