scenarios:
- name: francis2023_down_path
  map_file: ../../../maps/svg_maps/francis2023/francis2023_down_path.svg
  simulation_config:
    max_episode_steps: 400
    ped_density: 0.0
  single_pedestrians:
  - id: h1
    goal_poi: poi_h1_goal
  robot_config: {}
  metadata:
    figure: 7e
    archetype: down_path
    flow: uni
    behavior: none
    plausibility:
      status: unverified
      verified_on: null
      verified_by: null
      method: null
      notes: null
      metrics:
        min_distance: 2.4525620473833802
        mean_distance: 8.18640912848803
        robot_ped_within_5m_frac: 0.286921645008917
        ped_force_mean: 0.058679364586949403
        force_q95: 0.22723102640892362
      metrics_updated_on: '2026-01-30T14:19:28.225110+01:00'
  seeds:
  - 213
  - 214
  - 215
