scenarios:
- name: francis2023_perpendicular_traffic
  map_file: ../../../maps/svg_maps/francis2023/francis2023_perpendicular_traffic.svg
  simulation_config:
    max_episode_steps: 400
    ped_density: 0.1
  robot_config: {}
  metadata:
    figure: 7w
    archetype: perpendicular_traffic
    flow: perpendicular
    behavior: traffic
    plausibility:
      status: unverified
      verified_on: null
      verified_by: null
      method: null
      notes: null
      metrics:
        min_distance: 0.4192220190887409
        mean_distance: 4.977434194478542
        robot_ped_within_5m_frac: 0.5035460992907801
        ped_force_mean: 0.33362709455788936
        force_q95: 1.113636138112578
      metrics_updated_on: '2026-01-30T10:19:37.701701+01:00'
  seeds:
  - 267
  - 268
  - 269
