scenarios:
- name: francis2023_narrow_doorway
  map_file: ../../../maps/svg_maps/francis2023/francis2023_narrow_doorway.svg
  simulation_config:
    max_episode_steps: 400
    ped_density: 0.0
  single_pedestrians:
  - id: h1
    goal_poi: poi_h1_goal
  robot_config: {}
  metadata:
    figure: 7k
    archetype: narrow_doorway
    flow: bi
    behavior: none
  seeds:
  - 225
  - 226
  - 227
