scenarios:
- name: francis2023_crowd_navigation
  map_file: ../../../maps/svg_maps/francis2023/francis2023_crowd_navigation.svg
  simulation_config:
    max_episode_steps: 400
    ped_density: 0.08
  robot_config: {}
  metadata:
    figure: 7u
    archetype: crowd_navigation
    flow: crowd
    behavior: crowd
  seeds:
  - 261
  - 262
  - 263
