scenarios:
- name: francis2023_exiting_elevator
  map_file: ../../../maps/svg_maps/francis2023/francis2023_exiting_elevator.svg
  simulation_config:
    max_episode_steps: 400
    ped_density: 0.0
  single_pedestrians:
  - id: h1
    goal_poi: poi_h1_goal
  robot_config: {}
  metadata:
    figure: 7o
    archetype: exiting_elevator
    flow: exit
    behavior: none
    plausibility:
      status: unverified
      verified_on: null
      verified_by: null
      method: null
      notes: null
      metrics:
        min_distance: 1.9274021081195187
        mean_distance: 3.672120444714254
        robot_ped_within_5m_frac: 0.7592158661361399
        ped_force_mean: 0.3153608063487094
        force_q95: 0.7462034994191002
      metrics_updated_on: '2026-01-30T14:19:28.225110+01:00'
  seeds:
  - 237
  - 238
  - 239
