scenarios:
- name: francis2023_intersection_no_gesture
  map_file: ../../../maps/svg_maps/francis2023/francis2023_intersection_no_gesture.svg
  simulation_config:
    max_episode_steps: 400
    ped_density: 0.0
  single_pedestrians:
  - id: h1
    goal_poi: poi_h1_goal
  robot_config: {}
  metadata:
    figure: 7f
    archetype: intersection_no_gesture
    flow: perpendicular
    behavior: none
    plausibility:
      status: unverified
      verified_on: null
      verified_by: null
      method: null
      notes: null
      metrics:
        min_distance: 3.256009818678403
        mean_distance: 6.449710826583615
        robot_ped_within_5m_frac: 0.36428571428571427
        ped_force_mean: 0.08252575762299313
        force_q95: 0.34353609243869504
      metrics_updated_on: '2026-01-30T10:19:37.701701+01:00'
  seeds:
  - 216
  - 217
  - 218
