scenarios:
- name: francis2023_entering_room
  map_file: ../../../maps/svg_maps/francis2023/francis2023_entering_room.svg
  simulation_config:
    max_episode_steps: 400
    ped_density: 0.0
  single_pedestrians:
  - id: h1
    goal_poi: poi_h1_goal
  robot_config: {}
  metadata:
    figure: 7l
    archetype: entering_room
    flow: enter
    behavior: none
    plausibility:
      status: unverified
      verified_on: null
      verified_by: null
      method: null
      notes: null
      metrics:
        min_distance: 7.867420498638671
        mean_distance: 12.331910760114203
        robot_ped_within_5m_frac: 0.0
        ped_force_mean: 0.20276778378876564
        force_q95: 0.46905547599656344
      metrics_updated_on: '2026-01-29T14:02:05.787139+01:00'
  seeds:
  - 228
  - 229
  - 230
