scenarios:
- name: francis2023_circular_crossing
  map_file: ../../../maps/svg_maps/francis2023/francis2023_circular_crossing.svg
  simulation_config:
    max_episode_steps: 400
    ped_density: 0.06
  robot_config: {}
  metadata:
    figure: 7x
    archetype: circular_crossing
    flow: circular
    behavior: traffic
    plausibility:
      status: unverified
      verified_on: null
      verified_by: null
      method: null
      notes: null
      metrics:
        min_distance: 2.0585364782135662
        mean_distance: 3.3030352009664035
        robot_ped_within_5m_frac: 0.5917009819448844
        ped_force_mean: 7.162734045862031
        force_q95: 29.256663468988307
      metrics_updated_on: '2026-01-30T14:19:28.225110+01:00'
  seeds:
  - 270
  - 271
  - 272
